version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4 # Official pgAdmin Docker image
    container_name: pgadmin_pratise
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com # pgAdmin login email
      PGADMIN_DEFAULT_PASSWORD: admin # pgAdmin password
    ports:
      - "5050:80" # Maps pgAdmin web UI to localhost:5050
    depends_on:
      - postgres # Ensure PostgreSQL starts first

volumes:
  postgres_data:
